### ISSUE TITLE
`ps` failed

### ISSUE THREAD

**Issue by yubiuser** [pi-hole/PADD#303]
If you leave it for a little while the layout goes a little crazy... but it still doesn't flicker...
![20221216_173707](https://user-images.githubusercontent.com/30553736/208134139-3b1cae01-262b-4395-aacc-2979faa0ce57.jpg)

_Originally posted by @FirstGeekDanny in https://github.com/pi-hole/PADD/issues/290#issuecomment-1355096366_

**Comment by yubiuser** [comment]
Somwhow `ps` failed.

https://github.com/pi-hole/PADD/blob/6676f562e074336241bd06807c60718bafa1b987/padd.sh#L416-L417

**Comment by rdwebdesign** [comment]
If `${ftlPID}` is empty, I see the same error, but I don't know how this is happening.

**Comment by rdwebdesign** [comment]
As a workaround we can add `2>/dev/null` to avoid the error:
```diff
  ftl_cpu="$(ps -p "${ftlPID}" -o %cpu 2>/dev/null | tail -n1 | tr -d '[:space:]')" 
  ftl_mem_percentage="$(ps -p "${ftlPID}" -o %mem 2>/dev/null | tail -n1 | tr -d '[:space:]')" 
```

**Comment by rdwebdesign** [comment]
I think the issue happens if FTL is restarted exactly at the same time PADD updates the screen.
The new PID is not updated immediately and the `ps` command fails showing an error message. After that, the error never goes away until restart PADD.

I saw a similar issue on PHP, when FTL is restarted via web interface.

**Comment by rdwebdesign** [comment]
We can also change the function "moveXOffset()" to print N spaces, instead of moving the cursor:

```diff sh
- printf '\e[%sC' "${xOffset}"
+ printf '%*s' "${xOffset}"
```

**Comment by DL6ER** [comment]
The test is broken. We should fix it rather than adding a workaround in form of `2> /dev/null`

``` bash
if [ -z ${ftlPID+x} ]; then
```
will *always* succeed as `+x` will substitute the variable by `x` if the variable is set. As we have
```
ftlPID=$(pidof pihole-FTL)
```
the variable will never be unset, but if it empty (FTL not running), the substitution will kick in and the test will succeed.

The test should read
``` bash
if [ -z "${ftlPID}" ]; then
```
instead.

**Comment by yubiuser** [comment]
Fix released with https://github.com/pi-hole/PADD/releases/tag/v3.10.0
